[workspace]
members = [".", "python"]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
strip = true

[package]
name = "small_world"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
byteorder = "1.5"

[dev-dependencies]
libc = "0.2"
proptest = { version = "1.6", default-features = false, features = ["std"] }

[[example]]
name = "geoid_offset"
path = "examples/egm96_geoid_offset.rs"
